Run the tests straight from the workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,7 +34,7 @@ jobs:
           ruby-version: ${{ matrix.ruby_version }}
           bundler-cache: true
       - name: Execute tests
-        run:  script/cibuild
+        run:  bundle exec rspec spec/test_jekyll-last-modified-at.rb
   j3:
     if: "!contains(github.event.commits[0].message, '[ci skip]')"
     name: "Jekyll ${{ matrix.jekyll_version }} (Ruby ${{ matrix.ruby_version }})"
@@ -58,4 +58,31 @@ jobs:
           ruby-version: ${{ matrix.ruby_version }}
           bundler-cache: true
       - name: Execute tests
-        run:  script/cibuild
+        run:  bundle exec rspec spec/test_jekyll-last-modified-at.rb
+  style_check:
+    if: "!contains(github.event.commits[0].message, '[ci skip]')"
+    name: "Code Style Check (Ruby ${{ matrix.ruby_version }})"
+    runs-on: 'ubuntu-latest'
+    strategy:
+      fail-fast: false
+      matrix:
+        ruby_version:
+        - 2.5
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 1000
+      - name: "Set up Ruby ${{ matrix.ruby_version }}"
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby_version }}
+          bundler-cache: true
+      - name: Check Style Offenses
+        run:  |
+          echo "Rubocop $(bundle exec rubocop --version)"
+          bundle exec rubocop -D -E
+          success=$?
+          if ((success != 0)); then
+            echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
+          fi
+          exit $success
